import type { Metadata } from "next";
import DocsShell from "../DocsShell";
import { mockCompatibility } from "../../lib/mock-data";
import "../docs.css";

export const metadata: Metadata = { title: "Compatibility — BaseCLF" };

export default function CompatibilityPage() {
  return <DocsShell active="Compatibility"><p className="docs-eyebrow">Reference</p><h1 id="overview">Know what carries over—and what changes.</h1><p className="docs-lede">BaseCLF aims for familiar client workflows on Cloudflare infrastructure. Compatibility is practical, not a promise that D1 behaves like Postgres.</p><h2 id="details">Capability matrix</h2><div className="docs-table-wrap"><table className="docs-table"><thead><tr><th>Capability</th><th>Status</th><th>Boundary</th></tr></thead><tbody>{mockCompatibility.map(([capability, status, boundary]) => <tr key={capability}><td>{capability}</td><td><span className={`docs-state ${status === "Supported" ? "supported" : status === "Partial" || status === "Planned" || status === "Off by default" ? "partial" : "unsupported"}`}>{status}</span></td><td>{boundary}</td></tr>)}</tbody></table></div><h2 id="caveats">How to read this page</h2><ul><li><strong>Supported</strong> means it runs on the shipped engine and is covered by its tests.</li><li><strong>Off by default</strong> means it exists and works; the default follows a measured cost, not a missing feature.</li><li><strong>Planned</strong> is roadmap language, not an available production feature.</li><li><strong>Not applicable</strong> is a property of SQLite rather than a gap.</li></ul><div className="docs-callout"><strong>Source of truth</strong><p>These rows mirror the compatibility tables in the engine repository&apos;s README, which are maintained against its tests. The full tables list every refused operator and every place the client differs from supabase-js.</p></div><div className="docs-footer-nav"><a href="/docs/policies">← Policy DSL</a><a href="/studio">Open Studio →</a></div></DocsShell>;
}
