import type { Metadata } from "next";
import Link from "next/link";
import DocsShell from "./DocsShell";
import "./docs.css";

export const metadata: Metadata = { title: "Docs", description: "Build a Supabase-compatible backend on Cloudflare." };

export default function DocsHome() {
  return <DocsShell active="Overview"><p className="docs-eyebrow">BaseCLF documentation</p><h1 id="overview">A backend you can understand before you ship.</h1><p className="docs-lede">BaseCLF assembles authentication, D1, R2 storage, instant APIs, and row-level policies into one Cloudflare-native workflow.</p><div className="docs-callout"><strong>What is real here</strong><p>The commands, policy documents, and API behavior in these docs match the shipped engine: <code>create-baseclf</code>, <code>baseclf policy</code>, and the <code>baseclf-js</code> client are on npm. Studio opens on fixture data; connecting a deployment makes the Simulator, Policies, Tables, Auth, and Health screens read that deployment for real, while Storage stays a fixture preview. Health reports the checks the deployment can run on itself; usage numbers are recorded against your Cloudflare account and are not read there.</p></div><h2 id="details">Choose your path</h2><div className="docs-table-wrap"><table className="docs-table"><thead><tr><th>Goal</th><th>Start here</th><th>What you get</th></tr></thead><tbody><tr><td>Launch a project</td><td><a href="/docs/quickstart">Quickstart →</a></td><td>Install, configure, deploy, and verify a first request.</td></tr><tr><td>Control data access</td><td><a href="/docs/policies">Policy DSL →</a></td><td>Rules, auth claims, rejection behavior, and SQL examples.</td></tr><tr><td>Check fit</td><td><a href="/docs/compatibility">Compatibility →</a></td><td>Supported features and deliberate caveats.</td></tr></tbody></table></div><h2 id="caveats">Important boundaries</h2><ul><li>BaseCLF runs in your Cloudflare account; it is not a hosted database service.</li><li>Direct database access (<code>wrangler d1 execute</code>, the D1 console) bypasses the policy engine by design.</li><li>Compatibility rows mirror the engine repository&apos;s README tables, which are maintained against its tests.</li></ul><div className="docs-footer-nav"><Link href="/">← Landing</Link><a href="/docs/quickstart">Quickstart →</a></div></DocsShell>;
}
