import type { Metadata } from "next";
import DocsShell from "../DocsShell";
import CopyButton from "../CopyButton";
import "../docs.css";

export const metadata: Metadata = { title: "Policy DSL" };

export default function PoliciesPage() {
  const policy = `{\n  "table": "posts",\n  "enabled": true,\n  "binds": {\n    "isPublished": { "status": { "_eq": "published" } },\n    "isAuthor": { "author_id": { "_eq": "$auth.uid" } }\n  },\n  "policies": [\n    {\n      "name": "read_own_or_published",\n      "for": "select",\n      "to": ["authenticated"],\n      "using": { "_or": [{ "$bind": "isPublished" }, { "$bind": "isAuthor" }] },\n      "columns": ["id", "title", "body", "status", "author_id", "created_at"]\n    }\n  ]\n}`;
  const sql = `select "posts"."id", "posts"."title", "posts"."body",\n       "posts"."status", "posts"."author_id", "posts"."created_at"\nfrom "posts"\nwhere (("posts"."status" = ?) or ("posts"."author_id" = ?))`;
  return <DocsShell active="Policy DSL"><p className="docs-eyebrow">Reference</p><h1 id="overview">Policy rules that stay close to the data.</h1><p className="docs-lede">Policies are JSON documents. The engine compiles them into parameterized SQL and attaches the predicate to every request; a table with no document refuses every caller.</p><h2 id="details">Claims and operators</h2><div className="docs-table-wrap"><table className="docs-table"><thead><tr><th>Expression</th><th>Meaning</th><th>Notes</th></tr></thead><tbody><tr><td><code>$auth.uid</code></td><td>The verified user id, from the JWT</td><td>Bound as a SQL parameter. Absent means the <code>anon</code> role.</td></tr><tr><td><code>$auth.email</code></td><td>The verified email</td><td>Bound as a SQL parameter.</td></tr><tr><td><code>$auth.app.*</code></td><td>Server-set metadata</td><td>Only operators and your server can write it, so policies may trust it.</td></tr><tr><td><code>$auth.user.*</code></td><td>User-editable metadata</td><td><strong>Refused when the document is saved.</strong> End users can write it themselves, so a policy reading it would be self-service escalation.</td></tr><tr><td><code>_eq _neq _gt _gte _lt _lte _like _is_null</code></td><td>Comparisons</td><td>Every value is a bound parameter, never spliced into SQL.</td></tr><tr><td><code>_in _and _or _not _exists</code></td><td>Composition</td><td><code>_in</code> compiles to <code>json_each</code> so a whole list costs one parameter; <code>_exists</code> is a correlated subquery for reaching related tables.</td></tr></tbody></table></div><h2>Example</h2><div className="docs-code"><header><span>posts.json · Policy document</span><CopyButton value={policy} /></header><pre><code>{policy}</code></pre></div><div className="docs-code"><header><span>Compiled SQL · Positional parameters</span><CopyButton value={sql} /></header><pre><code>{sql}</code></pre></div><h2 id="caveats">Refusal behavior</h2><p>A table with no document answers 404 for every caller. A denied read simply lacks the rows. A write that matches nothing answers 404 whether the row was absent or the policy withheld it: the two cases are deliberately indistinguishable, because a caller who could tell them apart could walk a range of ids and learn which exist. Writes compile to single guarded statements, so there is no partial state to clean up.</p><div className="docs-callout"><strong>Performance</strong><p>D1 bills rows scanned, not rows returned, so a policy column without an index is a recurring bill rather than a latency problem. <code>baseclf policy lint</code> names the columns and hands back the <code>CREATE INDEX</code> to paste, and every response carries an <code>x-baseclf-rows-read</code> header so you can watch it.</p></div><div className="docs-footer-nav"><a href="/docs/quickstart">← Quickstart</a><a href="/docs/compatibility">Compatibility →</a></div></DocsShell>;
}
