import type { Metadata } from "next";
import DocsShell from "../DocsShell";
import CopyButton from "../CopyButton";
import "../docs.css";

export const metadata: Metadata = { title: "Quickstart — BaseCLF" };

export default function QuickstartPage() {
  const create = `npx baseclf login\nnpx create-baseclf`;
  const policy = `{\n  "table": "posts",\n  "enabled": true,\n  "policies": [\n    {\n      "name": "read_published",\n      "for": "select",\n      "to": ["anon"],\n      "using": { "status": { "_eq": "published" } },\n      "columns": ["id", "title", "body", "status", "author_id", "created_at"]\n    }\n  ]\n}`;
  const verify = `npx baseclf policy apply posts.json --project your-project\n\ncurl https://your-project.your-subdomain.workers.dev/rest/v1/posts\n\nHTTP/2 200\n[{ "id": "p_1", "title": "Published by u_1", "status": "published" }]`;
  return <DocsShell active="Quickstart"><p className="docs-eyebrow">Guide · 10 minutes</p><h1 id="overview">Go from an empty Cloudflare account to your first protected query.</h1><p className="docs-lede">One command provisions a database, a bucket, and a Worker into your own account, then waits until the address answers. The commands on this page are the shipped ones, not placeholders.</p><div className="docs-callout"><strong>Two one-time things first</strong><p>Sign in with <code>npx baseclf login</code> (the credential stays on your machine; BaseCLF has no OAuth app of its own), and switch on R2 in the Cloudflare dashboard. R2 is off on a new account, and provisioning stops at that step until it is enabled.</p></div><h2 id="details">1. Create a deployment</h2><div className="docs-code"><header><span>Terminal</span><CopyButton value={create} /></header><pre><code>{create}</code></pre></div><p>It asks two questions, each with a default: a project name, which names the database, bucket, and Worker on your account, and your frontend origin, without which a browser on another origin cannot call the API. The signing secret is generated, never asked for.</p><h2>2. Expose a table</h2><p>A fresh deployment exposes nothing. A table without a policy document is a table nobody can reach, so there is no state where you forgot to turn security on. Save this as <code>posts.json</code>:</p><div className="docs-code"><header><span>posts.json · Policy document</span><CopyButton value={policy} /></header><pre><code>{policy}</code></pre></div><p>This grants one thing to one role: a caller who is not signed in may read published rows. Drafts are never granted, which is different from being excluded by a rule.</p><h2>3. Apply and verify</h2><div className="docs-code"><header><span>Terminal</span><CopyButton value={verify} /></header><pre><code>{verify}</code></pre></div><p>Two of the four seeded rows come back with no filter in the URL: the drafts are outside what this caller was granted. A policy change lands within about thirty seconds, so a request sent the instant <code>apply</code> returns can still see the previous answer.</p><div className="docs-note" id="caveats"><p>Direct database access, meaning <code>wrangler d1 execute</code> or the D1 console, bypasses the policy engine by design. Application traffic belongs on the API. Admin tokens belong in local tooling, never in a browser bundle.</p></div><div className="docs-footer-nav"><a href="/docs">← Overview</a><a href="/docs/policies">Policy DSL →</a></div></DocsShell>;
}
