"use client";

import { ReactNode, useState } from "react";
import { mockApiKeys, mockDataJobs, mockDeployments, mockInvoices, mockMigrations, mockQueues, mockRealtimeChannels, mockRestorePoints, mockTeamMembers, mockUsage, mockWebhooks } from "../../lib/mock-data";
import ExpansionShell from "../expansion/ExpansionShell";

function Heading({ kicker, title, copy, note }: { kicker: string; title: string; copy: string; note: ReactNode }) {
  return <div className="suite-heading"><div><span className="expansion-kicker">{kicker}</span><h2>{title}</h2><p>{copy}</p></div><span className="suite-note">{note}</span></div>;
}

function Toast({ message }: { message: string }) { return message ? <div className="expansion-toast" role="status"><i />{message}</div> : null; }
function useNotice() { const [notice, setNotice] = useState(""); const announce = (value: string) => { setNotice(value); window.setTimeout(() => setNotice(""), 2400); }; return { notice, announce }; }

export function MigrationsApp() {
  const [selected, setSelected] = useState(0); const [confirm, setConfirm] = useState(false); const { notice, announce } = useNotice(); const item = mockMigrations[selected];
  return <ExpansionShell active="Migrations" title="Migrations" eyebrow="field-notes / schema history"><Heading kicker="Schema changes you can review" title="Move the database forward without losing the trail." copy="Compare pending SQL with the applied history, then make the production boundary explicit." note={<><b>Mock migration ledger</b> No SQL is applied from this preview.</>} />
    <section className="suite-split"><div className="suite-list"><header><span>Migration ledger</span><small>1 pending · 3 applied</small></header>{mockMigrations.map((row, index) => <button key={row.version} className={selected === index ? "is-selected" : ""} onClick={() => setSelected(index)} type="button"><code>{row.version}</code><span><strong>{row.name}</strong><small>{row.statements} statements · {row.author}</small></span><b className={`pill ${row.state}`}>{row.state}</b></button>)}</div><article className="suite-detail"><header><div><span className="expansion-kicker">Migration {item.version}</span><h3>{item.name}</h3></div><button type="button" disabled={item.state !== "pending"} onClick={() => setConfirm(true)}>Review & apply</button></header><div className="migration-meta"><span><small>Created</small><strong>{item.created}</strong></span><span><small>Author</small><strong>{item.author}</strong></span><span><small>Target</small><strong>launch-notes-prod</strong></span></div><pre className="suite-code"><code>{`ALTER TABLE posts ADD COLUMN visibility TEXT\n  NOT NULL DEFAULT 'private';\n\nCREATE INDEX idx_posts_visibility\n  ON posts (visibility);\n\nUPDATE posts SET visibility = 'public'\n  WHERE status = 'published';`}</code></pre><aside className="risk-note"><b>Review boundary</b><p>Applying a migration changes schema and data. The real product will require a fresh restore bookmark and typed confirmation.</p></aside></article></section>
    {confirm && <div className="expansion-modal-backdrop"><form className="expansion-dialog" onSubmit={(event) => { event.preventDefault(); setConfirm(false); announce("Mock migration review completed. No schema changed."); }}><span className="expansion-kicker">Production boundary</span><h3>Apply migration 0007?</h3><p>This preview records the interaction only. A connected product would create a restore point before applying SQL.</p><label>Type the database name<input required placeholder="launch-notes-prod" pattern="launch-notes-prod" /></label><div><button type="button" onClick={() => setConfirm(false)}>Cancel</button><button type="submit">Confirm mock apply</button></div></form></div>}<Toast message={notice} />
  </ExpansionShell>;
}

export function BackupsApp() {
  const [restore, setRestore] = useState(false); const { notice, announce } = useNotice();
  return <ExpansionShell active="Backups" title="Backups & data transfer" eyebrow="field-notes / D1 recovery"><Heading kicker="Recovery before regret" title="Go back to a known moment—or move your data out." copy="Time Travel restore points, SQL imports, and long-term exports share one calm operational view." note={<><b>D1-aligned concept</b> Restore overwrites the database in place and must be confirmed.</>} />
    <section className="backup-layout"><article className="timeline-card"><header><div><span>Time Travel</span><small>Point-in-time recovery · fixture</small></div><button type="button" onClick={() => setRestore(true)}>Restore database</button></header><div className="timeline-rule">Now <i /></div>{mockRestorePoints.map((point, index) => <div className="restore-point" key={point.bookmark}><i /><span><strong>{point.time}</strong><small>{point.note}</small></span><code>{point.bookmark}</code>{index === 0 && <b>Current</b>}</div>)}</article><aside className="backup-summary"><span className="expansion-kicker">Recovery window</span><strong>30 days</strong><p>Displayed as a paid-plan fixture. Actual retention depends on the connected Cloudflare plan.</p><dl><div><dt>Database</dt><dd>launch-notes-prod</dd></div><div><dt>Current size</dt><dd>42.8 MB</dd></div><div><dt>Last bookmark</dt><dd>14:32 UTC</dd></div></dl></aside></section>
    <section className="job-card"><header><div><span>Import & export jobs</span><small>SQL files only in this interface concept</small></div><div><button type="button" onClick={() => announce("Mock import flow opened.")}>Import SQL</button><button type="button" onClick={() => announce("Mock export queued to R2.")}>Export to R2</button></div></header><div className="simple-table"><div className="simple-head"><span>File</span><span>Direction</span><span>Destination</span><span>Size</span><span>Status</span></div>{mockDataJobs.map((job) => <div key={job.name}><strong>{job.name}</strong><span>{job.kind}</span><code>{job.destination}</code><span>{job.size}</span><b className="state-positive">{job.state}</b></div>)}</div></section>
    {restore && <div className="expansion-modal-backdrop"><form className="expansion-dialog danger-dialog" onSubmit={(event) => { event.preventDefault(); setRestore(false); announce("Restore simulation complete. Database was not changed."); }}><span className="expansion-kicker">Destructive operation</span><h3>Restore in place?</h3><p>A real D1 restore overwrites the current database and cancels in-flight work. This preview performs no operation.</p><label>Type RESTORE launch-notes-prod<input required pattern="RESTORE launch-notes-prod" /></label><div><button type="button" onClick={() => setRestore(false)}>Cancel</button><button type="submit">Simulate restore</button></div></form></div>}<Toast message={notice} />
  </ExpansionShell>;
}

export function WebhooksApp() {
  const [tab, setTab] = useState<"Webhooks" | "Queues">("Webhooks"); const { notice, announce } = useNotice();
  return <ExpansionShell active="Webhooks & Queues" title="Webhooks & Queues" eyebrow="field-notes / event delivery"><Heading kicker="Events that arrive with context" title="Send the signal now. Finish the work reliably." copy="Inspect outbound webhooks and background queues without turning delivery mechanics into an infrastructure project." note={<><b>Fixture traffic</b> Success rates, backlog, and retries are illustrative.</>} />
    <div className="suite-tabs"><button className={tab === "Webhooks" ? "is-selected" : ""} onClick={() => setTab("Webhooks")} type="button">Webhooks</button><button className={tab === "Queues" ? "is-selected" : ""} onClick={() => setTab("Queues")} type="button">Queues</button><span>{tab === "Webhooks" ? "3 endpoints" : "3 queues"}</span></div>
    {tab === "Webhooks" ? <section className="event-grid">{mockWebhooks.map((hook) => <article key={hook.name}><header><span className={`event-dot ${hook.state}`} /><b className={`pill ${hook.state}`}>{hook.state}</b></header><h3>{hook.name}</h3><code>{hook.event}</code><p>{hook.endpoint}</p><footer><span>Success <strong>{hook.success}</strong></span><button type="button" onClick={() => announce(`Mock delivery sent for ${hook.name}.`)}>Send test</button></footer></article>)}<button className="add-card" type="button" onClick={() => announce("Mock webhook builder opened.")}><b>＋</b><span>Add webhook</span></button></section> : <section className="queue-console"><div className="queue-overview"><span><small>Messages waiting</small><strong>201</strong></span><span><small>Retried today</small><strong>11</strong></span><span><small>Dead-lettered</small><strong>4</strong></span></div><div className="simple-table"><div className="simple-head queue-row"><span>Queue</span><span>Consumer</span><span>Backlog</span><span>Retries</span><span>Health</span></div>{mockQueues.map((queue) => <div className="queue-row" key={queue.name}><strong>{queue.name}</strong><code>{queue.consumer}</code><span>{queue.backlog}</span><span>{queue.retries}</span><b className={`queue-state ${queue.state}`}>{queue.state}</b></div>)}</div><aside className="queue-note"><b>Dead-letter boundary</b><p>Messages that exhaust configured retries can move to a separate DLQ. This table does not consume or purge anything.</p><button type="button" onClick={() => announce("Mock DLQ inspector opened.")}>Inspect dead letters</button></aside></section>}<Toast message={notice} />
  </ExpansionShell>;
}

export function DeploymentsApp() {
  const [selected, setSelected] = useState(0); const [rollback, setRollback] = useState(false); const { notice, announce } = useNotice(); const version = mockDeployments[selected];
  return <ExpansionShell active="Deployments" title="Deployments" eyebrow="field-notes / Worker versions"><Heading kicker="Know exactly what is serving" title="A version is a snapshot. A deployment decides what goes live." copy="Review code versions, traffic state, and rollback impact from one release timeline." note={<><b>Mock release history</b> Storage state is not part of a Worker version.</>} />
    <section className="deploy-layout"><div className="deploy-list"><header><span>Version history</span><button type="button" onClick={() => announce("Mock version uploaded; traffic unchanged.")}>Upload version</button></header>{mockDeployments.map((row, index) => <button key={row.version} className={selected === index ? "is-selected" : ""} type="button" onClick={() => setSelected(index)}><i /><span><strong>{row.version} · {row.message}</strong><small>{row.hash} · {row.actor} · {row.time}</small></span><b>{row.traffic}%</b></button>)}</div><article className="deploy-detail"><header><div><span className="expansion-kicker">Selected version</span><h3>{version.version} · {version.hash}</h3></div><button type="button" disabled={version.state === "active"} onClick={() => setRollback(true)}>Roll back to this version</button></header><div className="traffic-map"><span><small>Active traffic</small><strong>{version.traffic}%</strong></span><div><i style={{ width: `${Math.max(version.traffic, 2)}%` }} /></div><code>{version.state === "active" ? "Currently serving all routes" : "Not currently serving traffic"}</code></div><div className="change-list"><header>Included in this Worker version</header>{["Bundled Worker code", "Static assets", "Bindings configuration", "Compatibility settings"].map((value) => <p key={value}><i />{value}</p>)}</div><aside className="risk-note"><b>Storage boundary</b><p>D1, R2, KV, and Durable Object data are not rolled back with Worker code.</p></aside></article></section>
    {rollback && <div className="expansion-modal-backdrop"><form className="expansion-dialog" onSubmit={(event) => { event.preventDefault(); setRollback(false); announce(`Mock rollback to ${version.version} completed.`); }}><span className="expansion-kicker">Create a new deployment</span><h3>Roll back to {version.version}?</h3><p>This would route 100% of traffic to the selected version. Connected resources remain unchanged.</p><div><button type="button" onClick={() => setRollback(false)}>Cancel</button><button type="submit">Confirm mock rollback</button></div></form></div>}<Toast message={notice} />
  </ExpansionShell>;
}

export function TeamApp() {
  const [selected, setSelected] = useState(0); const { notice, announce } = useNotice(); const member = mockTeamMembers[selected];
  return <ExpansionShell active="Team" title="Team & roles" eyebrow="field-notes / access"><Heading kicker="Small team, explicit access" title="Give people the work they need—not every key." copy="Invite collaborators, assign product roles, and understand effective project access before saving." note={<><b>Mock identity data</b> Invites and role changes are not sent.</>} />
    <section className="team-layout"><div className="team-list"><header><span>Workspace members</span><button onClick={() => announce("Mock invite dialog opened.")} type="button">Invite member</button></header>{mockTeamMembers.map((row, index) => <button className={selected === index ? "is-selected" : ""} onClick={() => setSelected(index)} type="button" key={row.email}><i>{row.name.split(" ").map((word) => word[0]).join("")}</i><span><strong>{row.name}</strong><small>{row.email}</small></span><b className={`pill ${row.state}`}>{row.state}</b></button>)}</div><article className="member-detail"><header><div><span className="expansion-kicker">Effective access</span><h3>{member.name}</h3></div><button type="button" onClick={() => announce("Mock role change saved locally.")}>Save role</button></header><label>Workspace role<select value={member.role} onChange={() => undefined}><option>Owner</option><option>Developer</option><option>Analyst</option></select></label><div className="permission-grid">{[["Database", "Read & write"], ["Functions", member.role === "Analyst" ? "View only" : "Deploy"], ["Logs", "View"], ["Billing", member.role === "Owner" ? "Manage" : "No access"]].map(([area, access]) => <span key={area}><small>{area}</small><strong>{access}</strong></span>)}</div><aside><b>Cloudflare remains separate</b><p>BaseCLF workspace roles do not automatically grant access to the connected Cloudflare account.</p></aside></article></section><Toast message={notice} />
  </ExpansionShell>;
}

export function ApiKeysApp() {
  const [create, setCreate] = useState(false); const [revealed, setRevealed] = useState(false); const { notice, announce } = useNotice();
  return <ExpansionShell active="API Keys" title="API Keys" eyebrow="field-notes / credentials"><Heading kicker="Credentials with a narrow job" title="Know which key exists, what it can do, and when it was used." copy="Public client credentials and privileged project keys stay visibly separate from Cloudflare account tokens." note={<><b>Masked fixtures</b> No usable credential appears in this preview.</>} />
    <section className="key-card"><header><div><span>Project credentials</span><small>BaseCLF-scoped keys · not Cloudflare API tokens</small></div><button type="button" onClick={() => { setCreate(true); setRevealed(false); }}>Create key</button></header><div className="simple-table"><div className="simple-head key-row"><span>Name</span><span>Key prefix</span><span>Scope</span><span>Last used</span><span>Action</span></div>{mockApiKeys.map((key) => <div className="key-row" key={key.name}><strong>{key.name}</strong><code>{key.prefix}</code><span>{key.scope}</span><small>{key.lastUsed}</small><button type="button" onClick={() => announce(`Revoke confirmation opened for ${key.name}.`)}>Revoke</button></div>)}</div><aside className="credential-boundary"><i>!</i><div><strong>Secret keys belong on the server.</strong><p>They are shown once after creation, stored hashed, and cannot be retrieved later in the proposed product flow.</p></div></aside></section>
    {create && <div className="expansion-modal-backdrop"><form className="expansion-dialog" onSubmit={(event) => { event.preventDefault(); if (!revealed) setRevealed(true); else { setCreate(false); announce("Mock key recorded; no credential was created."); } }}><span className="expansion-kicker">New project credential</span><h3>{revealed ? "Copy this key now" : "Choose a narrow scope"}</h3>{revealed ? <><p>This one-time value is fake and cannot authenticate anywhere.</p><code className="one-time-key">bclf_secret_mock_demo_not_valid_9da31</code></> : <><label>Key name<input required defaultValue="Server integration" /></label><label>Scope<select defaultValue="Functions: invoke"><option>Functions: invoke</option><option>Logs: read</option><option>Deployments: write</option></select></label></>}<div><button type="button" onClick={() => setCreate(false)}>Cancel</button><button type="submit">{revealed ? "I copied it" : "Create mock key"}</button></div></form></div>}<Toast message={notice} />
  </ExpansionShell>;
}

export function UsageApp() {
  const { notice, announce } = useNotice();
  return <ExpansionShell active="Usage & Billing" title="Usage & Billing" eyebrow="field-notes / account"><Heading kicker="Capacity without surprise" title="See what your app uses before usage becomes a question." copy="Project activity, product allowances, and invoices live together while Cloudflare infrastructure charges remain distinct." note={<><b>Illustrative numbers only</b> Pricing and metering contracts are not finalized.</>} />
    <section className="usage-grid">{mockUsage.map((metric) => <article key={metric.label}><span>{metric.label}</span><strong>{metric.value}</strong><div><i style={{ width: `${metric.percent}%` }} /></div><small>{metric.percent}% · {metric.limit}</small></article>)}</section><section className="billing-layout"><article className="usage-chart"><header><div><span>API requests</span><small>Last 14 days · fixture</small></div><strong>184,220</strong></header><div className="bar-chart" aria-label="Mock API request trend">{[34,48,39,62,54,71,64,82,58,69,91,76,88,67].map((height, index) => <i style={{ height: `${height}%` }} key={index} />)}</div><footer><span>Aug 06</span><span>Aug 19</span></footer></article><aside className="billing-card"><span className="expansion-kicker">Current product plan</span><h3>Builder preview</h3><strong>$24 <small>/ projected month</small></strong><p>Mock BaseCLF subscription. Cloudflare resource usage would be billed by Cloudflare under the owner’s account.</p><button type="button" onClick={() => announce("Mock plan comparison opened.")}>Compare plans</button></aside></section><section className="invoice-card"><header><span>Invoices</span><button type="button" onClick={() => announce("Mock billing portal opened.")}>Billing details</button></header>{mockInvoices.map((invoice) => <div key={invoice.period}><strong>{invoice.period}</strong><span>{invoice.date}</span><b>{invoice.amount}</b><small>{invoice.state}</small><button type="button">View</button></div>)}</section><Toast message={notice} />
  </ExpansionShell>;
}

export function RealtimeApp() {
  const [selected, setSelected] = useState(0); const { notice, announce } = useNotice(); const channel = mockRealtimeChannels[selected];
  return <ExpansionShell active="Realtime" title="Realtime concept" eyebrow="field-notes / planned"><Heading kicker="Presence and events, designed first" title="Understand the channel before you open the socket." copy="A product concept for subscriptions, presence, and event inspection on a Durable Objects and WebSockets foundation." note={<><b>Planned — not enabled</b> This screen makes no production availability claim.</>} />
    <div className="planned-banner"><span>CONCEPT</span><p>Realtime is outside the current MVP contract. Every connection, event, and control below is a static fixture.</p><button type="button" onClick={() => announce("Interest recorded locally for this preview.")}>Register interest</button></div><section className="realtime-layout"><div className="channel-list"><header><span>Channels</span><small>{mockRealtimeChannels.length} fixtures</small></header>{mockRealtimeChannels.map((row, index) => <button className={selected === index ? "is-selected" : ""} onClick={() => setSelected(index)} key={row.name} type="button"><i /><span><strong>{row.name}</strong><small>{row.connections} connected · {row.events} events</small></span></button>)}</div><article className="channel-detail"><header><div><span className="expansion-kicker">Channel inspector</span><h3>{channel.name}</h3></div><span className="concept-status"><i /> simulated</span></header><div className="channel-metrics"><span><small>Connections</small><strong>{channel.connections}</strong></span><span><small>Events today</small><strong>{channel.events.toLocaleString()}</strong></span><span><small>Presence</small><strong>{channel.presence ? "Enabled" : "Off"}</strong></span></div><div className="event-stream"><header><span>Event stream</span><small>Paused fixture</small></header>{[["14:32:08", "postgres_changes", "posts", "UPDATE"], ["14:31:54", "presence", "usr_maya_chen", "SYNC"], ["14:31:12", "broadcast", "cursor", "MOVE"]].map((event) => <div key={event[0]}><time>{event[0]}</time><b>{event[1]}</b><code>{event[2]}</code><span>{event[3]}</span></div>)}</div><aside className="architecture-note"><b>Proposed foundation</b><p>A Worker accepts the upgrade, while a Durable Object coordinates channel state and hibernating WebSocket connections.</p></aside></article></section><Toast message={notice} />
  </ExpansionShell>;
}
