"use client";

import { ReactNode } from "react";
import { mockDataJobs, mockDeployments, mockMigrations, mockQueues, mockRealtimeChannels, mockRestorePoints, mockUsage, mockWebhooks } from "../../lib/mock-data";
import ComingSoon from "../expansion/ComingSoon";
import ExpansionShell from "../expansion/ExpansionShell";

function Heading({ kicker, title, copy, note }: { kicker: string; title: string; copy: string; note: ReactNode }) {
  return <div className="suite-heading"><div><span className="expansion-kicker">{kicker}</span><h2>{title}</h2><p>{copy}</p></div><span className="suite-note">{note}</span></div>;
}

export function MigrationsApp() {
  const selected = 0; const item = mockMigrations[selected];
  return <ExpansionShell active="Migrations" title="Migrations" eyebrow="field-notes / schema history"><Heading kicker="Schema changes you can review" title="Move the database forward without losing the trail." copy="Compare pending SQL with the applied history, then make the production boundary explicit." note={<><b>Mock migration ledger</b> No SQL is applied from this preview.</>} />
    <ComingSoon surface="Migrations" note="The real path is wrangler d1 migrations, which the CLI will grow into as baseclf migrate."><section className="suite-split"><div className="suite-list"><header><span>Migration ledger</span><small>1 pending · 3 applied</small></header>{mockMigrations.map((row, index) => <button key={row.version} className={selected === index ? "is-selected" : ""} type="button"><code>{row.version}</code><span><strong>{row.name}</strong><small>{row.statements} statements · {row.author}</small></span><b className={`pill ${row.state}`}>{row.state}</b></button>)}</div><article className="suite-detail"><header><div><span className="expansion-kicker">Migration {item.version}</span><h3>{item.name}</h3></div><button type="button" disabled={item.state !== "pending"}>Review & apply</button></header><div className="migration-meta"><span><small>Created</small><strong>{item.created}</strong></span><span><small>Author</small><strong>{item.author}</strong></span><span><small>Target</small><strong>launch-notes-prod</strong></span></div><pre className="suite-code"><code>{`ALTER TABLE posts ADD COLUMN visibility TEXT\n  NOT NULL DEFAULT 'private';\n\nCREATE INDEX idx_posts_visibility\n  ON posts (visibility);\n\nUPDATE posts SET visibility = 'public'\n  WHERE status = 'published';`}</code></pre><aside className="risk-note"><b>Review boundary</b><p>Applying a migration changes schema and data. The real product will require a fresh restore bookmark and typed confirmation.</p></aside></article></section></ComingSoon>
  </ExpansionShell>;
}

export function BackupsApp() {
  return <ExpansionShell active="Backups" title="Backups & data transfer" eyebrow="field-notes / D1 recovery"><Heading kicker="Recovery before regret" title="Go back to a known moment—or move your data out." copy="Time Travel restore points, SQL imports, and long-term exports share one calm operational view." note={<><b>D1-aligned concept</b> Restore overwrites the database in place and must be confirmed.</>} />
    <ComingSoon surface="Backups" note="The real path is D1 Time Travel, the point-in-time recovery window a Cloudflare account already has."><section className="backup-layout"><article className="timeline-card"><header><div><span>Time Travel</span><small>Point-in-time recovery · fixture</small></div><button type="button">Restore database</button></header><div className="timeline-rule">Now <i /></div>{mockRestorePoints.map((point, index) => <div className="restore-point" key={point.bookmark}><i /><span><strong>{point.time}</strong><small>{point.note}</small></span><code>{point.bookmark}</code>{index === 0 && <b>Current</b>}</div>)}</article><aside className="backup-summary"><span className="expansion-kicker">Recovery window</span><strong>30 days</strong><p>Displayed as a paid-plan fixture. Actual retention depends on the connected Cloudflare plan.</p><dl><div><dt>Database</dt><dd>launch-notes-prod</dd></div><div><dt>Current size</dt><dd>42.8 MB</dd></div><div><dt>Last bookmark</dt><dd>14:32 UTC</dd></div></dl></aside></section>
    <section className="job-card"><header><div><span>Import & export jobs</span><small>SQL files only in this interface concept</small></div><div><button type="button">Import SQL</button><button type="button">Export to R2</button></div></header><div className="simple-table"><div className="simple-head"><span>File</span><span>Direction</span><span>Destination</span><span>Size</span><span>Status</span></div>{mockDataJobs.map((job) => <div key={job.name}><strong>{job.name}</strong><span>{job.kind}</span><code>{job.destination}</code><span>{job.size}</span><b className="state-positive">{job.state}</b></div>)}</div></section></ComingSoon>
  </ExpansionShell>;
}

export function WebhooksApp() {
  return <ExpansionShell active="Webhooks & Queues" title="Webhooks & Queues" eyebrow="field-notes / event delivery"><Heading kicker="Events that arrive with context" title="Send the signal now. Finish the work reliably." copy="Inspect outbound webhooks and background queues without turning delivery mechanics into an infrastructure project." note={<><b>Fixture traffic</b> Success rates, backlog, and retries are illustrative.</>} />
    <ComingSoon surface="Webhooks and queues" note="The real path is the V2 outbox: change events written in the same batch() as the write, delivered through Cloudflare Queues.">
    <div className="suite-tabs"><button className="is-selected" type="button">Webhooks</button><button type="button">Queues</button><span>3 endpoints</span></div>
    <section className="event-grid">{mockWebhooks.map((hook) => <article key={hook.name}><header><span className={`event-dot ${hook.state}`} /><b className={`pill ${hook.state}`}>{hook.state}</b></header><h3>{hook.name}</h3><code>{hook.event}</code><p>{hook.endpoint}</p><footer><span>Success <strong>{hook.success}</strong></span><button type="button">Send test</button></footer></article>)}<button className="add-card" type="button"><b>＋</b><span>Add webhook</span></button></section>
    <section className="queue-console"><div className="queue-overview"><span><small>Messages waiting</small><strong>201</strong></span><span><small>Retried today</small><strong>11</strong></span><span><small>Dead-lettered</small><strong>4</strong></span></div><div className="simple-table"><div className="simple-head queue-row"><span>Queue</span><span>Consumer</span><span>Backlog</span><span>Retries</span><span>Health</span></div>{mockQueues.map((queue) => <div className="queue-row" key={queue.name}><strong>{queue.name}</strong><code>{queue.consumer}</code><span>{queue.backlog}</span><span>{queue.retries}</span><b className={`queue-state ${queue.state}`}>{queue.state}</b></div>)}</div><aside className="queue-note"><b>Dead-letter boundary</b><p>Messages that exhaust configured retries can move to a separate DLQ. This table does not consume or purge anything.</p><button type="button">Inspect dead letters</button></aside></section></ComingSoon>
  </ExpansionShell>;
}

export function DeploymentsApp() {
  const version = mockDeployments[0];
  return <ExpansionShell active="Deployments" title="Deployments" eyebrow="field-notes / Worker versions"><Heading kicker="Know exactly what is serving" title="A version is a snapshot. A deployment decides what goes live." copy="Review code versions, traffic state, and rollback impact from one release timeline." note={<><b>Mock release history</b> Storage state is not part of a Worker version.</>} />
    <ComingSoon surface="Deployments" note="The real path is the Cloudflare versions API, read with the credential the local Studio already holds."><section className="deploy-layout"><div className="deploy-list"><header><span>Version history</span><button type="button">Upload version</button></header>{mockDeployments.map((row, index) => <button key={row.version} className={index === 0 ? "is-selected" : ""} type="button"><i /><span><strong>{row.version} · {row.message}</strong><small>{row.hash} · {row.actor} · {row.time}</small></span><b>{row.traffic}%</b></button>)}</div><article className="deploy-detail"><header><div><span className="expansion-kicker">Selected version</span><h3>{version.version} · {version.hash}</h3></div><button type="button" disabled={version.state === "active"}>Roll back to this version</button></header><div className="traffic-map"><span><small>Active traffic</small><strong>{version.traffic}%</strong></span><div><i style={{ width: `${Math.max(version.traffic, 2)}%` }} /></div><code>{version.state === "active" ? "Currently serving all routes" : "Not currently serving traffic"}</code></div><div className="change-list"><header>Included in this Worker version</header>{["Bundled Worker code", "Static assets", "Bindings configuration", "Compatibility settings"].map((value) => <p key={value}><i />{value}</p>)}</div><aside className="risk-note"><b>Storage boundary</b><p>D1, R2, KV, and Durable Object data are not rolled back with Worker code.</p></aside></article></section></ComingSoon>
  </ExpansionShell>;
}

export function UsageApp() {
  return <ExpansionShell active="Usage & Billing" title="Usage & Billing" eyebrow="field-notes / account"><Heading kicker="Capacity without surprise" title="See what your app uses before usage becomes a question." copy="Project activity and product allowances in one view, while Cloudflare infrastructure charges remain distinct." note={<><b>Illustrative numbers only</b> Pricing and metering contracts are not finalized.</>} />
    <ComingSoon surface="Usage metering" note="The real path is the GraphQL analytics API plus the x-baseclf-rows-read header every data response already carries."><section className="usage-grid">{mockUsage.map((metric) => <article key={metric.label}><span>{metric.label}</span><strong>{metric.value}</strong><div><i style={{ width: `${metric.percent}%` }} /></div><small>{metric.percent}% · {metric.limit}</small></article>)}</section><section className="billing-layout"><article className="usage-chart"><header><div><span>API requests</span><small>Last 14 days · fixture</small></div><strong>184,220</strong></header><div className="bar-chart" aria-label="Mock API request trend">{[34,48,39,62,54,71,64,82,58,69,91,76,88,67].map((height, index) => <i style={{ height: `${height}%` }} key={index} />)}</div><footer><span>Aug 06</span><span>Aug 19</span></footer></article><aside className="billing-card"><span className="expansion-kicker">Current product plan</span><h3>Builder preview</h3><strong>$24 <small>/ projected month</small></strong><p>Mock BaseCLF subscription. Cloudflare resource usage would be billed by Cloudflare under the owner’s account. Invoices live in the owner’s Cloudflare account, so they are not shown here.</p><button type="button">Compare plans</button></aside></section></ComingSoon>
  </ExpansionShell>;
}

export function RealtimeApp() {
  const channel = mockRealtimeChannels[0];
  return <ExpansionShell active="Realtime" title="Realtime concept" eyebrow="field-notes / planned"><Heading kicker="Presence and events, designed first" title="Understand the channel before you open the socket." copy="A product concept for subscriptions, presence, and event inspection on a Durable Objects and WebSockets foundation." note={<><b>Planned — not enabled</b> This screen makes no production availability claim.</>} />
    <div className="planned-banner"><span>CONCEPT</span><p>Realtime is outside the current MVP contract. Every connection, event, and control below is a static fixture.</p></div><div className="planned-scope" inert><section className="realtime-layout"><div className="channel-list"><header><span>Channels</span><small>{mockRealtimeChannels.length} fixtures</small></header>{mockRealtimeChannels.map((row, index) => <button className={index === 0 ? "is-selected" : ""} key={row.name} type="button"><i /><span><strong>{row.name}</strong><small>{row.connections} connected · {row.events} events</small></span></button>)}</div><article className="channel-detail"><header><div><span className="expansion-kicker">Channel inspector</span><h3>{channel.name}</h3></div><span className="concept-status"><i /> simulated</span></header><div className="channel-metrics"><span><small>Connections</small><strong>{channel.connections}</strong></span><span><small>Events today</small><strong>{channel.events.toLocaleString()}</strong></span><span><small>Presence</small><strong>{channel.presence ? "Enabled" : "Off"}</strong></span></div><div className="event-stream"><header><span>Event stream</span><small>Paused fixture</small></header>{[["14:32:08", "postgres_changes", "posts", "UPDATE"], ["14:31:54", "presence", "usr_maya_chen", "SYNC"], ["14:31:12", "broadcast", "cursor", "MOVE"]].map((event) => <div key={event[0]}><time>{event[0]}</time><b>{event[1]}</b><code>{event[2]}</code><span>{event[3]}</span></div>)}</div><aside className="architecture-note"><b>Proposed foundation</b><p>A Worker accepts the upgrade, while a Durable Object coordinates channel state and hibernating WebSocket connections.</p></aside></article></section></div>
  </ExpansionShell>;
}
